"""second  migration

Revision ID: 4bf2b75b05c7
Revises: ae332c625abc
Create Date: 2025-03-21 19:19:23.943426

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '4bf2b75b05c7'
down_revision: Union[str, None] = 'ae332c625abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
