"""initial migration

Revision ID: ae332c625abc
Revises: 
Create Date: 2025-03-21 19:10:59.459341

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ae332c625abc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
